use strict;
use warnings;

package FourStore;

use XSLoader;
use XS::Object::Magic;

our $VERSION = '0.01';

my @flags = qw(
FS_RID_NULL
FS_RID_GONE

FS_BIND_MODEL
FS_BIND_SUBJECT
FS_BIND_PREDICATE
FS_BIND_OBJECT
FS_BIND_DISTINCT
FS_BIND_OPTIONAL
FS_BIND_UNION
FS_QUERY_CONSOLE_OUTPUT

FS_BIND_SAME_MASK
FS_BIND_SAME_XXXX
FS_BIND_SAME_XXAA
FS_BIND_SAME_XAXA
FS_BIND_SAME_XAAX
FS_BIND_SAME_XAAA
FS_BIND_SAME_AXXA
FS_BIND_SAME_AXAX
FS_BIND_SAME_AXAA
FS_BIND_SAME_AAXX
FS_BIND_SAME_AAXA
FS_BIND_SAME_AAAX
FS_BIND_SAME_AAAA
FS_BIND_SAME_AABB
FS_BIND_SAME_ABAB
FS_BIND_SAME_ABBA

FS_QUERY_RESTRICTED

FS_BIND_BY_SUBJECT
FS_BIND_BY_OBJECT
FS_BIND_END
FS_BIND_PRICE
FS_QUERY_EXPLAIN
FS_QUERY_COUNT
FS_QUERY_DEFAULT_GRAPH
);

use Sub::Exporter;

Sub::Exporter->import(-setup => {
    exports => [@flags],
    groups  => { default => [@flags] },
});

XSLoader::load(__PACKAGE__, $VERSION);

1;
